FROM python:alpine

ENV PYTHONUNBUFFERED=1

WORKDIR /src
COPY ./src /src/

RUN pip install --upgrade pip
COPY requirements.txt /src/
RUN pip install -r requirements.txt

ENTRYPOINT celery -A settings worker -l info
