# Generated by Django 4.0.5 on 2022-08-12 12:44

import django.db.models.deletion
import django_extensions.db.fields
import easy_thumbnails.fields
from django.db import migrations, models

import apps.post.processors.file_path_processor


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(
                    upload_to=apps.post.processors.file_path_processor.FilePathProcessor.get_photo_path,
                    verbose_name='post image')),
            ],
            options={
                'verbose_name': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, help_text='Добавьте текст поста.', max_length=2000,
                                          verbose_name='post body')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, unique=True,
                                                                     verbose_name='post slug')),
                ('creation_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'post',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='tag name')),
                ('post', models.ForeignKey(help_text='Пост, к которому относится тег.',
                                           on_delete=django.db.models.deletion.CASCADE, related_name='tags',
                                           to='post.post', verbose_name='tag post')),
            ],
            options={
                'verbose_name': 'tag',
            },
        ),
    ]
