# Generated by Django 4.0.5 on 2022-08-12 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(help_text='Создатель поста.', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='posts', to=settings.AUTH_USER_MODEL,
                                    verbose_name='creator of the post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(help_text='Лайки, поставленные посту.', through='likes.Like',
                                         to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(help_text='Пост, к которому относится изображение.',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='post.post',
                                    verbose_name='photo post'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='tag',
            order_with_respect_to='post',
        ),
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to='creator',
        ),
        migrations.AlterOrderWithRespectTo(
            name='photo',
            order_with_respect_to='post',
        ),
    ]
