# Generated by Django 4.0.5 on 2022-07-22 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('likes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, поставивший лайк.',
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='the user that liked the post'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='like',
            order_with_respect_to='post',
        ),
    ]
