# Generated by Django 4.0.5 on 2022-08-13 09:54
from django.apps import apps as applications
from django.db import migrations, transaction

Like = applications.get_model('likes', 'Like')
User = applications.get_model('user', 'User')


@transaction.atomic
def create_initial_likes(apps, schema_editor):
    user1 = User.objects.get(username='dafna')
    user2 = User.objects.get(username='richard')

    likes = []
    for post in user2.posts.all():
        likes.append(Like(post=post, user=user1, _order=0))
    likes.append(Like(post=user1.posts.last(), user=user2, _order=0))
    Like.objects.bulk_create(likes)


@transaction.atomic
def revert_create_initial_likes(apps, schema_editor):
    Like.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('likes', '0003_initial'),
        ('post', '0003_add_initial_posts'),
    ]

    operations = [
        migrations.RunPython(create_initial_likes, revert_create_initial_likes)
    ]
