# Generated by Django 4.0.5 on 2022-08-13 09:54

from django.db import migrations

from apps.likes.models import Like
from apps.user.models import User


def create_test_likes(apps, schema_editor):
    user1 = User.objects.get(username='dafna')
    user2 = User.objects.get(username='richard')

    for post in user2.posts.all():
        like = Like(post=post, user=user1)
        like.save()
    like = Like(post=user1.posts.last(), user=user2)
    like.save()


def revert_create_test_likes(apps, schema_editor):
    Like.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('likes', '0003_initial'),
        ('post', '0003_add_test_posts'),
    ]

    operations = [
        migrations.RunPython(create_test_likes, revert_create_test_likes)
    ]
