# Generated by Django 4.0.5 on 2022-08-12 12:45

from django.db import migrations

from apps.user.models import User
from test_data.user import test_user_data


def create_test_users(apps, schema_editor):
    for username, email, password in test_user_data:
        User.objects.create_user(username=username, email=email, password=password)


def revert_create_test_users(apps, schema_editor):
    User.objects.last().delete()
    User.objects.last().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_users, revert_create_test_users)
    ]
