# Generated by Django 4.0.5 on 2022-07-22 22:51

import django_extensions.db.fields
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True,
                                                               help_text='Только файлы формата .JPG или .PNG!',
                                                               upload_to='user/avatars/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Биография пользователя.', max_length=1000,
                                   verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, unique=True,
                                                              verbose_name='user slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Обязательное поле.', max_length=254, unique=True,
                                    verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
    ]
