# Generated by Django 4.0.5 on 2022-08-12 12:45
from django.apps import apps as applications
from django.db import migrations, transaction

from initial_data.user_data import user_data

User = applications.get_model('user', 'User')


@transaction.atomic
def create_initial_users(apps, schema_editor):
    User.objects.bulk_create(
        [User(username=username, email=email, password=password) for username, email, password in user_data]
    )


@transaction.atomic
def revert_create_initial_users(apps, schema_editor):
    User.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_users, revert_create_initial_users)
    ]
