# Generated by Django 4.0.5 on 2022-08-12 12:45

from django.db import migrations

from apps.user.models import User
from initial_data.user_data import user_data


def create_initial_users(apps, schema_editor):
    for username, email, password in user_data:
        User.objects.create_user(username=username, email=email, password=password)


def revert_create_initial_users(apps, schema_editor):
    User.objects.last().delete()
    User.objects.last().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_users, revert_create_initial_users)
    ]
