# Generated by Django 4.0.5 on 2022-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
