# Generated by Django 4.0.5 on 2022-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True,
                                    help_text='Upload files in .JPG or .PNG formats only! .HEIC is not supported yet..',
                                    upload_to='user/avatars/'),
        ),
    ]
