# Generated by Django 4.0.5 on 2022-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True,
                                    help_text='Только файлы формата .JPG или .PNG! Формат .HEIC на данный момент не поддерживается.',
                                    upload_to='user/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Обязательное поле.', max_length=254, unique=True,
                                    verbose_name='email address'),
        ),
    ]
