# Generated by Django 4.0.5 on 2022-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0009_alter_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True,
                                    help_text='Только файлы формата .JPG или .PNG! Формат .HEIC на данный момент не поддерживается.',
                                    upload_to='user/avatars/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='biography'),
        ),
    ]
